image: docker:latest

services:
  - docker:dind

stages:
  - "Validate"
  - "Build"
  - "Test"
  - "Analyze"
  - "Release"
  - "Deploy"

##
## Validate
##
shellcheck:
  stage: "Validate"
  image: cardboardci/shellcheck:latest
  script:
    - shellcheck provision/*.sh

hadolint:
  stage: "Validate"
  image: cardboardci/hadolint:latest
  script:
    - hadolint Dockerfile*

##
## Build
##
build:
  stage: "Build"
  script:
    - docker build --pull \
      --label org.label-schema.name="rsvg" \
      --label org.label-schema.vendor="cardboardci" \
      --label org.label-schema.build-date="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
      --label org.label-schema.vcs-ref="${CI_COMMIT_SHORT_SHA}" \
      -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" . \
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE"

##
## Test
##
bats:
  stage: "Test"
  script:
    - apk add -U curl
    - curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 && chmod +x container-structure-test-linux-amd64 && mv container-structure-test-linux-amd64 /usr/local/bin/structure-test
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
    - structure-test test --image "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --config tests/primary.yaml
    - structure-test test --image "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" --config tests/metadata.yaml

##
## Analyze
##
# audit:
#   stage: "Analyze"
#   script:
#     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
#     - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

##
## Release
##
# tag:
#   stage: "Release"
#   script:
#     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
#     - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

##
## Deploy
##
# docker.hub:
#   stage: "Deploy"
#   script:
#     - source deploy/hub.docker.config
#     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
#     - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#     - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "docker.io/${HUB_NAMESPACE}/${HUB_PROJECT}:edge"
#     - echo "$HUB_REGISTRY_PASSWORD" | docker login -u "$HUB_REGISTRY_USER" --password-stdin
#     - docker push "docker.io/${HUB_NAMESPACE}/${HUB_PROJECT}:edge"
#   only:
#     - master
    
# quay.io:
#   stage: "Deploy"
#   script:
#     - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
#     - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#     - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "quay.io/$HUB_NAMESPACE/$HUB_PROJECT:alpha"
#     - docker login -u "$HUB_REGISTRY_USER" -p "$HUB_REGISTRY_PASSWORD" quay.io
#     - docker push "quay.io/$HUB_NAMESPACE/$HUB_PROJECT:alpha"
#   only:
#     - master
